### ISSUE TITLE
[BUG] - Incorrect Conversion of Decimal Numbers to Words in Total Cost

### ISSUE THREAD

**Issue by JeevanJoshi4434** [al1abb/invoify#536]
#### **Summary**  
There is a problem during the conversion of decimal numbers to words in the Total Cost field. Decimal portions are currently displayed as fractions (e.g., `25/100`), which is not user-friendly.

---

#### **Steps to Reproduce**  
1. Navigate to the Total Cost calculation functionality.  
2. Enter a decimal value (e.g., `121.25`).  
3. Check the conversion of the total cost to words.

---

#### **Expected Behavior**  
The decimal portion should be converted to currency-specific terms for better readability. Examples:  
- For INR: `One hundred twenty-one Rupees and Twenty-Five Paisa`.  
- For other currencies: `One hundred twenty-one Dollars and Fifty Cents`.

---

#### **Actual Behavior**  
The decimal portion is displayed as a fraction (e.g., `25/100`), making it less intuitive for end-users.

---

#### **Screenshot**  
![image](https://github.com/user-attachments/assets/2e188d15-802b-44f7-a32b-0327e6d993b5)

---

#### **Suggested Fix**  
Update the conversion logic to handle currency-specific terms for the decimal portion.

---

#### **Request**  
I would like to take ownership of fixing this issue. Please assign this to me so I can implement and test the required changes. This will not only help improve the feature but also contribute to my experience with open-source contributions, allowing me to give back to the community while enhancing the project's quality.

**Comment by JeevanJoshi4434** [comment]
@al1abb  in my latest commit I've fixed the conversion Issue and also addressed bot feedback to correct code format and logic. kindly checkout and let me know if I can open a PR.

**Comment by al1abb** [comment]
> @al1abb in my latest commit I've fixed the conversion Issue and also addressed bot feedback to correct code format and logic. kindly check out the PR.

@JeevanJoshi4434, I checked your pull request. It looks good, but there is a small bug. When you initially fill in the form with INR currency, it shows you the correct words. But once you switch it to another currency (like USD), it still shows the words for INR. 

![image](https://github.com/user-attachments/assets/eff1b6be-0cdf-4c5e-b50c-63d528ecfa7a)

**Comment by JeevanJoshi4434** [comment]
Hii @al1abb, I've fixed the issue, I forgot to add currency variable to `useEffect` hook's dependency which was causing the issue. Now it is working fine. you can check it out once vercel will deploy the preview.

**Comment by al1abb** [comment]
Good job @JeevanJoshi4434

**Comment by JeevanJoshi4434** [comment]
thanks @al1abb
